myfield: '#edd342'
primaryColor: '#ffffff'
secondColor: '#f1bd19'
tertiaryColor: '#d0d0c2'
primaryLogo:
  user/themes/brandguide/assets/Primary-Vertical---Black.png:
    name: Primary-Vertical---Black.png
    path: user/themes/brandguide/assets/Primary-Vertical---Black.png
    type: image/png
    size: 5956
    file: user/themes/brandguide/assets/Primary-Vertical---Black.png
    route: null
primaryTextColor: '#353d38'
secondTextColor: '#353d38'
tertiaryTextColor: '#353d38'
secondaryColor: '#f1bd19'
secondaryTextColor: '#353d38'
quaternaryColor: '#fab28a'
quaternaryTextColor: '#353d38'
testText: testing!
primaryLogoVertical:
  user/themes/brandguide/assets/Primary-Vertical---Black.png:
    name: Primary-Vertical---Black.png
    type: image/png
    size: 3393
    path: user/themes/brandguide/assets/Primary-Vertical---Black.png
primaryLogoHorizontal:
  user/themes/brandguide/assets/Primary-Horizontal---Black.png:
    name: Primary-Horizontal---Black.png
    type: image/png
    size: 4475
    path: user/themes/brandguide/assets/Primary-Horizontal---Black.png
