title: Brandguide
author:
  name: Firebelly
  email: developer@firebellydesign.com
taxonomies:
  - category
  - tag
metadata:
  description: 'Firebelly Brand Guide'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
primaryColor: '#f1bd19'
