title: 'FLOR Brand Guide'
author:
  name: Firebelly
  email: developer@firebellydesign.com
taxonomies:
  - category
  - tag
metadata:
  description: 'FLOR Brand Guide'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
primaryColor: '#f1bd19'
googleAnalytics: UA-998109-51
