title: Text
'@extends': default

form:
  fields:
    tabs:

      fields:
        assets:
          type: tab
          title: Assets
          fields:
            header.assets:
              name: assets
              type: list
              label: Assets

              fields:
                .title:
                  type: text
                  label: Title
                .file:
                  label: Choose media
                  type: pagemediaselect

        advanced:
          fields:
            columns:
              fields:
                column1:
                  fields:
                    name:
                      default: modular/text
                      '@data-options': '\Grav\Common\Page\Pages::modularTypes'
            overrides:
              fields:
                header.template:
                  default: modular/text
                  '@data-options': '\Grav\Common\Page\Pages::modularTypes'

        content:
          fields:
            uploads:
              label: Page Media (first one will be displayed next to your content)
            header.sidenote:
              type: textarea
              label: Sidenote
