form:
  fields:
    brandAssets:
      type: section
      title: Brand Assets
      underline: true

      fields:
        columns:
          type: columns
          fields:
            column1:
              type: column
              fields:
                primaryLogoVertical:
                  type: file
                  label: Primary Brand Logo - Vertical
                  destination: 'user/themes/brandguide/assets'
                  accept:
                    - image/*
                  multiple: false
            column2:
              type: column
              fields:
                primaryLogoHorizontal:
                  type: file
                  label: Primary Brand Logo - Horizontal
                  destination: 'user/themes/brandguide/assets'
                  accept:
                    - image/*
                  multiple: false

    brandcolors:
      type: section
      title: Brand Colors
      underline: true

      fields:
        primaryColor:
          type: colorpicker
          label: Primary Background Color
        primaryTextColor:
          type: colorpicker
          label: Primary Text Color
        secondaryColor:
          type: colorpicker
          label: Secondary Background Color
        secondaryTextColor:
          type: colorpicker
          label: Secondary Text Color
        tertiaryColor:
          type: colorpicker
          label: Tertiary Background Color
        quaternaryColor:
          type: colorpicker
          label: Quaternary Background Color
        quinaryColor:
          type: colorpicker
          label: Quinary Background Color
        senaryColor:
          type: colorpicker
          label: Senary Background Color
        septenaryColor:
          type: colorpicker
          label: Septenary Background Color